<?xml version="1.0" encoding="utf-8"?><Database Name="CPC" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=CPC;User ID=sa" SettingsObjectName="LINQtoSQL_ex1.Properties.Settings" SettingsPropertyName="CPCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ListPrice" Member="ListPrice">
    <Type Name="ListPrice">
      <Column Name="ProductID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Prices" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>